version: "3.9"
services:
  kaggle:
    image: "$DOCKER_DEVELOPMENT_IMAGE"
    ports:
      - "8900:8787"
      - "3900:3838"
    environment:
      DISABLE_AUTH: "true"
    volumes:
      - type: "bind"
        source: "$GITHUBCOM_PATH/kaggle-lead"
        target: "/home/rstudio"
      - type: "bind"
        source: $LOCAL_RENV_CACHE
        target: "/renv/cache"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
